# Generated by Django 5.1.7 on 2025-06-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopon',
            name='number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
