# Generated by Django 5.1.7 on 2025-06-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0002_alter_coopon_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopon',
            name='number',
            field=models.CharField(default=0, max_length=100, unique=True),
        ),
    ]
