# Generated by Django 5.1.7 on 2025-07-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0004_coopon_icool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopon_icool',
            name='usetime',
            field=models.DateTimeField(null=True),
        ),
    ]
